[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.partitions = partitions.csv
board_upload.flash_size = 8MB
lib_deps = 
    adafruit/Adafruit LSM6DS @ ^4.7.0
    adafruit/Adafruit GC9A01A @ ^1.1.0
    adafruit/Adafruit GFX Library @ ^1.11.9
    adafruit/Adafruit BusIO @ ^1.14.5
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4
    bblanchon/ArduinoJson @ ^7.0.0
    adafruit/Adafruit DRV2605 Library @ ^1.2.4
    esphome/ESP32-audioI2S @ ^2.0.7
